### addition  +
### subtraction  -
### multiplication  *
### division  /
### reminder %
### power **
### floor division / /

# Day1

In [15]:
a=45
b=4
c=a + b
d=a - b


In [16]:
print(a)
print(b)
print(c)

type(c)
type(d)



45
4
49


int

In [ ]:
a = 56
b = 67
d = a + b

In [17]:
print(d)
type(d)

41


int

In [ ]:
#DIVISION
a = 67
b = 56
c = a / b


In [18]:
print(c)
type(c)

49


int

In [20]:
#REMINDER
a = 45
b = 67
c = a % b


In [21]:
print(c)
type(c)

45


int

In [22]:
#POWER
a = 56
b = 45
c = a ** b
print(c)
type(c)

4660808027410506132900915088997417305944355117847144307414511042169984019070976


int

In [23]:
#FLOOR
a = 87
b = 43
c = a // b
print(c)
type(c)

2


int

In [24]:
#boolean
#<
x =45
y =10.6
x < y



False

In [28]:
#>
x =45
y =10.6
x > y


True

In [29]:
#>=
x =45
y =10.6
x >= y

True

In [30]:
#<=
x =45
y =10.6
x <= y

False

In [31]:
# ==
x =45
y =10.6
x == y


False

In [33]:
x =45
y =45
x == y

True

In [34]:
# !=
x = 45
y = 10.6
x != y

True

In [35]:
#Logical operaters
True and True  --- True
True and False  --- False
False and True  --- True
False and False  --- False




False

In [37]:
True or True  --- True
True or False  --- False
False or True  --- True
False or False  --- False

0

In [1]:
c = [203,'Hyderabad',45,True,False,78,175,34.90]
c[2]

45

In [2]:
c[0]

203

In [3]:
c[1]

'Hyderabad'

In [4]:
c[-1]

90

In [5]:
c[-3]

175

In [6]:
c[7]

34

In [7]:
c[7]

34

In [7]:
#c = [203,'Hyderabad',45,True,False,78,175,34.90]
#c = [start : end]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2204730587.py, line 2)

In [5]:
c=[203,'Hyderabad',45,True,False,78,175,34.90]
c[ 4:6]
c[2: ]

[45, True, False, 78, 175, 34.9]

In [14]:
c[1:7:2]

['Hyderabad', True, 78]

NameError: name 'c' is not defined

In [ ]:
c=[203,'Hyderabad',45,True,False,78,175,34.90,]

In [7]:
c[2:]

[45, True, False, 78, 175, 34.9]

In [ ]:
#list methods
#append 
#insert
#extend
#pop
#remove
#clear
#count

In [3]:
c

[203, 'Hyderabad', 45, True, False, 78, 175, 34.9]

In [10]:
#length of list
len(c)

NameError: name 'c' is not defined

In [9]:
c.append('India')

NameError: name 'c' is not defined

In [11]:
c=[203,'Hyderabad',45,True,False,78,175,34.90]


In [12]:
len(c)

8

In [22]:
c.append('India')
c

[90, 'India']

In [21]:
c.insert(3,90)
c


[90]

In [15]:
c.pop(5)

False

In [16]:
c

[203, 'Hyderabad', 45, 90, True, 78, 175, 34.9, 'India']

In [17]:
c.clear()

In [20]:
c

[]

In [26]:
c


[90, 'India']

In [28]:
c.remove(90)
c

['India']

In [30]:
c.count('India')
c

['India']

In [31]:
d=[6,3,9,4,1,3,0,8.7,45,43,89]
d

[6, 3, 9, 4, 1, 3, 0, 8.7, 45, 43, 89]

In [35]:
del(d)

NameError: name 'd' is not defined

In [36]:
d

NameError: name 'd' is not defined

In [1]:
h = (90,45,6)
h

(90, 45, 6)

In [2]:
type(h)

tuple

In [3]:
##only two operations int tuple
h.index(45)

1

In [4]:
s ={34,56,7}
s

{7, 34, 56}

In [5]:
type(s)

set

In [6]:
#add is only used for set to add the element
s.add(90)

In [7]:
s

{7, 34, 56, 90}

In [14]:
s.remove(56)
s

{7, 90}

In [8]:
y = {45,79,90,214}
y

{45, 79, 90, 214}

In [10]:
s.difference(y)

{7, 34, 56}

In [15]:
s.intersection(y)

{90}

In [16]:
y.intersection(s)

{90}

In [17]:
s.union(y)

{7, 45, 79, 90, 214}

In [18]:
s.symmetric_difference(y)

{7, 45, 79, 214}

In [19]:
a=(50,70,80,90)
a

(50, 70, 80, 90)

In [20]:
d=list(a)
d

[50, 70, 80, 90]

In [22]:
d.append(40)
d

[50, 70, 80, 90, 40, 40]

In [ ]:
# a=tuple(d)
a

# day5

In [3]:
d = {'a': 4, 'b': 7, 'c':2}
d

{'a': 4, 'b': 7, 'c': 2}

In [4]:
type(d)

dict

In [5]:
d ={101: 9,102: 7,103: 2}
d

{101: 9, 102: 7, 103: 2}

In [8]:
d[101]=9
d

{101: 9, 102: 7, 103: 2, 104: 80}

In [9]:
d.update({104: 80})
d

{101: 9, 102: 7, 103: 2, 104: 80}

In [15]:
d.get(101)
d

{101: 4000, 103: 2, 104: 80}

In [10]:
del d[102]
d

{101: 9, 103: 2, 104: 80}

In [12]:
d.update({101:4000})
d

{101: 4000, 103: 2, 104: 80}

In [16]:

d[104]= [1000,5000,6000,7000]
d

{101: 4000, 103: 2, 104: [1000, 5000, 6000, 7000]}

In [17]:
d[101]
d

{101: 4000, 103: 2, 104: [1000, 5000, 6000, 7000]}

In [18]:
d[101]

4000

In [19]:
d[104][0:3]

[1000, 5000, 6000]

In [22]:
d.update({103:(30,40,50,60,70)})
d

{101: 4000, 103: (30, 40, 50, 60, 70), 104: [1000, 5000, 6000, 7000]}

In [23]:
d[103]

(30, 40, 50, 60, 70)

In [24]:
type(d)

dict

In [27]:
type(d[104])

list

In [ ]:
d[105]=('a':(30,50,70),'b':(1000,5000,7000,9000),'c':['K',('L':(11,12))])

# day6

In [ ]:
if condition:
    task1 block of code
elif condition2:
    task1 block of code
elif condition3:
    task3 block of code 
else:
    task4 block of code


In [2]:
x

9

In [1]:
x = 9
if x%2==0:
    print("Even")
else:
    print("odd")

odd


In [3]:
y='karthik'
y

'karthik'

In [4]:
y.isalpha()


True

In [8]:
name='Rishika'

In [10]:
if name.isalpha()==True:
    print('Accept')
else:
    print('Name should not contain digits and symbols')

Accept


In [12]:
name.isalpha()

True

In [13]:
x ='Telangana'
x

'Telangana'

In [14]:
x ='mumbai'
x

'mumbai'

In [15]:
x ='maharshtra'
x

'maharshtra'

In [20]:
x ='wow'
x

'wow'

In [21]:
if x.isalpha()==x:
    
    print('Accept')
else:
    print('Name should not contain digits and symbols')

Name should not contain digits and symbols


In [23]:
x.isalpha()

True

x='maha'
if x[0].lower()=='m':
    print('yes')
else:
    print("no")

In [25]:
x[0].lower()=='m'

True

In [35]:
x = "bye"
if x[0].upper()=='b'or'y'or'e':
    print('yes')
else:
    print("no")

yes


# Day7

In [ ]:
#for
#while


In [2]:
x=45
while x<10:
    print('yes',x)
    x=x+1
    
    
    
    

x=45
while x<10:
    print('yes',x)
    x=x+1
    
    
    
    

In [1]:
x=35
while x>10:
    print('yes',x)
    x=x-5
    
    
    
    

yes 35
yes 30
yes 25
yes 20
yes 15


In [2]:
y=[40,20,60,80,50,30,60,90]
y


[40, 20, 60, 80, 50, 30, 60, 90]

In [3]:
y+5

TypeError: can only concatenate list (not "int") to list

In [5]:
y*5
y

[40, 20, 60, 80, 50, 30, 60, 90]

In [6]:
world=[40,20,80,50,30,60,90]
world


[40, 20, 80, 50, 30, 60, 90]

In [12]:
for i in world:
    print(3.14*i*i)

5024.0
1256.0
20096.0
7850.0
2826.0
11304.0
25434.000000000004


In [13]:
gate=[50,70,89,75,90,45]
gate

[50, 70, 89, 75, 90, 45]

In [30]:
area=[]
for i in gate:
    area.append(5.14*i*i)

    

In [31]:
area

[12850.0, 25185.999999999996, 40713.939999999995, 28912.5, 41634.0, 10408.5]

In [33]:
type(gate)
gate

[50, 70, 89, 75, 90, 45]

In [34]:
num=[39,45,66,93,90,78,67,87,89,93,24,59,49,91]
num

[39, 45, 66, 93, 90, 78, 67, 87, 89, 93, 24, 59, 49, 91]

In [41]:
for i in num:
    if(i% 2=0):
        print('even')
        else:
            print('odd')

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (494901156.py, line 2)

In [43]:
j=[]
k=[]
for i in num:
    if i%2==0:
        j.append(i)
    else:
        k.append(i)

In [44]:
j

[66, 90, 78, 24]

In [45]:
k

[39, 45, 93, 67, 87, 89, 93, 59, 49, 91]

In [48]:
num1=[39,45,93,67,87,89,93,59,49,91]


In [49]:
str(num1)

'[39, 45, 93, 67, 87, 89, 93, 59, 49, 91]'

In [51]:
d=num1[0]

In [52]:
d

39

In [55]:
h=[]
for i in num:
    a=str(i)
    b=a.replace('9','2')
    c=int(b)
    h.append(c)

In [56]:
h

[32, 45, 66, 23, 20, 78, 67, 87, 82, 23, 24, 52, 42, 21]

In [57]:
a='solutiOns'
a

'solutiOns'

In [2]:
x='software'
y=''

for i in x:
    if i.lower() not in ('s','o'):
        y+=i
        


In [3]:
for i in x:
    print(i)

s
o
f
t
w
a
r
e


# Day8

In [1]:
def functionname(parameter):
    block of code
    return output

SyntaxError: invalid syntax (3462563280.py, line 2)

In [16]:
def calArea(r):
    a=3.14*r*r
    return a

In [19]:
w=calArea(r=10)
w


314.0

In [18]:
type(w)

float

In [20]:
def d_to_inr(x):
    return x*85

In [25]:
a=d_to_inr(15)
a

1275

In [24]:
b=d_to_inr(15)
b

1275

In [26]:
b+a

2550

In [32]:
a=print("India")
a

India


In [35]:
def aor(l,w):
    area=l*w
    return area

In [36]:
aor(w=5,l=10)

50

In [37]:
aor(20,15)

300

In [38]:
aor(l=10,w=5)

50

In [9]:
def area(radius,length,width):
    aoc=3.14*radius*radius
    aor=length*width
    return {'Area Of Rect':aor,'Area of Circle':aoc}

In [10]:
aor,aoc=area(radius=10,length=20,width=5)
aor

'Area Of Rect'

In [11]:
aoc

'Area of Circle'

In [12]:
aor

'Area Of Rect'

In [21]:
t='HyderabAAd 500008 Telangana'
t

'HyderabAAd 500008 Telangana'

In [24]:
def count_num_alpha(x):
    c=0
    d=0
    for i in x:
        if i.isalpha():
            c+=1
        elif i.isnumeric():    
            d+=1
    return {'Number of alphabets':c,'Number of digits':d}        
    

In [25]:
def remove_

NameError: name 'd' is not defined

# Day12

In [2]:
import numpy as np

In [1]:
j = [4,6,2,8,9];

In [1]:
numpy              Array operations

pandas             Data manipulation and analysis

matplotlib         Graphical Analysis

Sklearn            Machine learning algorithms and techniques

statsmodels        Statistical analysis

scipy              statistical analysis


SyntaxError: invalid syntax (2270501605.py, line 1)

In [4]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [15]:
d=.array(j)
d

SyntaxError: invalid syntax (427450670.py, line 1)

In [9]:
s=[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]
s

([4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60])

In [10]:
type(s)

tuple

arr1.ndim

In [14]:
arr1.size

NameError: name 'arr1' is not defined

In [11]:
w=d.reshape(3,2)
w

NameError: name 'd' is not defined

In [12]:
w.ndim
w

NameError: name 'w' is not defined

In [1]:
range(5,50,5)

range(5, 50, 5)

In [5]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [3]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [4]:
y=[]
x=[]
for i in range(len(j)):
    if i%2==0:
        x.append(j[i])
    else:
        y.append(j[i])

In [7]:
y

for i in j:
    print(i)

5
87
23
46
62
84
80
45
77
33
80


In [6]:
x

[5, 23, 62, 80, 77, 80]

In [4]:
import numpy as np


In [5]:
d=np.array([10,40,50,30,70])
d

array([10, 40, 50, 30, 70])

In [6]:
np.mean(d)

40.0

In [7]:
np.median(d)

40.0

In [8]:
np.var(d)

400.0

In [9]:
np.std(d)

20.0

In [10]:
np.max(d)

70

In [11]:
np.min(d)

10

In [12]:
np.quantile(d,0.25)

30.0

In [15]:
#Q1 = np.quantile(d,0.25)

In [21]:
#Q2 = np.quantile(d,0.5)

In [20]:
#Q3 = np.quantile(d,0.75)

In [13]:
np.random.rand()

0.22814931470888455

In [14]:
r=np.random.rand(100)
r

array([9.16519081e-01, 2.41188107e-01, 5.13547142e-01, 8.86728654e-01,
       6.99760926e-01, 4.72141039e-01, 6.94411196e-02, 7.14553999e-01,
       5.34475235e-01, 6.60102732e-01, 6.23536080e-01, 2.72850300e-01,
       6.64133897e-01, 1.28530934e-01, 4.19706385e-01, 9.07925959e-01,
       3.59732014e-01, 3.52975232e-01, 6.05275416e-01, 9.07306563e-01,
       1.87086413e-02, 6.26870887e-01, 1.98430953e-01, 9.12563148e-01,
       5.57645828e-01, 4.69460857e-01, 6.96295313e-01, 7.08295337e-01,
       5.10807872e-01, 1.71729792e-01, 8.21695686e-01, 2.26284950e-01,
       6.17927338e-01, 6.13178623e-01, 5.14391865e-01, 3.65542025e-02,
       5.48595062e-01, 5.61443708e-01, 4.80949861e-01, 1.10560078e-02,
       8.31050459e-02, 3.05375801e-02, 7.17375499e-01, 8.39399048e-01,
       7.89079272e-01, 6.20732263e-01, 3.28379296e-01, 1.83361551e-01,
       7.04205762e-01, 7.27286205e-01, 1.95358046e-01, 5.51089601e-01,
       8.44199661e-04, 7.75363940e-01, 3.49053435e-01, 8.36738903e-01,
      

In [15]:
r.size

100

In [16]:
r.shape

(100,)

In [17]:
r.ndim

1

In [18]:
np.random.rand(100,14)

array([[0.32133559, 0.66476022, 0.08683803, ..., 0.62487567, 0.76087899,
        0.41780621],
       [0.98260322, 0.64877563, 0.43478692, ..., 0.8945159 , 0.67319186,
        0.08099059],
       [0.59614754, 0.8706535 , 0.44369235, ..., 0.39270452, 0.23436568,
        0.87307063],
       ...,
       [0.6042411 , 0.19385225, 0.43151261, ..., 0.46864316, 0.48340564,
        0.21698066],
       [0.9076727 , 0.93897539, 0.79760526, ..., 0.06568974, 0.87192742,
        0.97705387],
       [0.42412518, 0.90746759, 0.81923599, ..., 0.12078479, 0.52845652,
        0.44269701]])

In [19]:
np.random.randn(10,4)

array([[-1.22161343,  1.27233597,  0.86036803, -0.90366539],
       [ 0.81064539, -1.84959736, -1.34190048,  0.83546004],
       [-0.65458188, -0.41305616, -0.54016302,  0.52507674],
       [-0.62517656,  0.54845622, -1.16405051, -0.21971042],
       [ 1.62717531,  0.29643903,  0.38691612,  0.50209588],
       [-0.89242169, -1.27676873, -0.53237251, -0.64585409],
       [ 0.75102611, -0.23704011, -0.52068853, -1.64753928],
       [-0.10701503, -0.6660043 , -0.80269567,  0.07090572],
       [ 1.83042915, -2.17395693,  0.28627432,  1.09785382],
       [-0.21406976, -1.9032628 ,  0.15998548,  0.40801341]])

In [20]:
np.random.randn(100,50)

array([[-0.12972381,  0.35530413, -0.60574777, ..., -1.26447148,
         0.5264451 ,  1.3740245 ],
       [ 0.3991449 ,  0.80736018,  0.24270109, ...,  0.04673415,
        -0.31439242, -1.46722678],
       [-2.16896182, -1.14260214,  0.37645334, ...,  1.0195262 ,
         0.81292766,  0.73648788],
       ...,
       [-0.36580866, -1.70867648,  1.980675  , ...,  0.94522503,
        -0.29299017,  0.8425507 ],
       [-2.02683339,  0.04528675, -0.55828578, ..., -0.30253481,
         0.61981303, -0.59256811],
       [-0.86304347,  1.1136949 ,  0.39105061, ..., -0.43394833,
         0.59468339, -1.31471391]])

In [21]:
np.random.randint(35,80)

39

# Day13

In [23]:
import numpy as np

In [24]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [25]:
d=[]
for i in h:
    d.append(i+7)

In [26]:
d

[37, 27, 12, 15, 16]

In [37]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [28]:
type(s)

tuple

In [38]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
    

In [39]:
s

(36, 4, 9, 81, 49, 25, 64)

In [40]:
m=[]
for i in s:
    if i>50:
        m.append(i)

In [41]:
m

[81, 64]

In [52]:
index=[]
for i in range(len(k)):
    if k[i]>50:
        index.append(i)
        index
        

In [54]:
index

[3, 6]

In [42]:
arr=np.array([20,50,30,70,80,40,36,54,23,90])

In [43]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 90])

In [44]:
arr+7

array([27, 57, 37, 77, 87, 47, 43, 61, 30, 97])

In [46]:
t = arr+7

In [47]:
t

array([27, 57, 37, 77, 87, 47, 43, 61, 30, 97])

In [48]:
arr*5

array([100, 250, 150, 350, 400, 200, 180, 270, 115, 450])

In [49]:
arr[arr>50]

array([70, 80, 54, 90])

In [50]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])