In [3]:
##week 1

import pandas as pd
from sklearn.impute import SimpleImputer
def generate_example_dataset():
    data = {
        'PassengerId':[1,2,3,4,5],
        'Name':['John','Jane','Bod','Alice','Charlie'],
        'Age':[22, None, 25, None, 30],
        'Fare':[7.25, 71.28, None, 8.05, 10.5],
        'Survived':[0, 1, 1, 0, 1]
    }
    return pd.DataFrame(data)
def clean_dataset(df):
    print("Original Dataset:")
    print(df)
    numeric_df = df.select_dtypes(include='number')
    imputer = SimpleImputer(strategy='mean')
    df_cleaned = pd.DataFrame(imputer.fit_transform(numeric_df), columns=numeric_df.columns)
    print("\nCleaned Dataset:")
    print(df_cleaned)
if __name__ == "__main__":
    example_dataset = generate_example_dataset()
    clean_dataset(example_dataset)
                            


Original Dataset:
   PassengerId     Name   Age   Fare  Survived
0            1     John  22.0   7.25         0
1            2     Jane   NaN  71.28         1
2            3      Bod  25.0    NaN         1
3            4    Alice   NaN   8.05         0
4            5  Charlie  30.0  10.50         1

Cleaned Dataset:
   PassengerId        Age   Fare  Survived
0          1.0  22.000000   7.25       0.0
1          2.0  25.666667  71.28       1.0
2          3.0  25.000000  24.27       1.0
3          4.0  25.666667   8.05       0.0
4          5.0  30.000000  10.50       1.0


In [19]:
## week 2.1

import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd
data_set = pd.read_csv('salary_Data.csv')
x = data_set.iloc[:,:-1].values
y = data_set.iloc[:,1].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)
x_pred=regressor.predict(x_train)
mtp.scatter(x_train,y_train,color='red')
mtp.plot(x_train,x_pred,color='green')
mtp.title("Salary vs Experience(Traning Dataset)")
mtp.xlabel("years of experience")
mtp.ylabel("salary(in rupees")
mtp.show()
mtp.scatter(x_test,y_test,color='blue')

mtp.plot(x_train,x_pred,color='red')
mtp.title("Salary vs Experience(Traning Dataset)")
mtp.xlabel("years of experience")
mtp.ylabel("salary(in rupees")
mtp.show()

FileNotFoundError: [Errno 2] No such file or directory: 'salary_Data.csv'

In [ ]:
#week 2.2

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
diabetes = datasets.load_diabetes()
diabetes_X = diabetes.data[:, np.newaxis, 2]
x = diabetes.data[:, np.newaxis, 2]
x_train = x[:-30]
x_test = x[-30:]
y_train = diabetes.target[:-30]
y_test = diabetes.target[-30:]
regr = linear_model.LinearRegression()
regr.fit(x_train, y_train)
y_pred = regr.predict(x_test)
print('Coefficients: \n', regr.coef_)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print('Variance score: %.2f' % r2_score(y_test, y_pred))
plt.scatter(x_test, y_test, color='blue')
plt.plot(x_test, y_pred, color='blue', linewidth=3)
plt.xticks(())
plt.yticks(())
plt.show()


In [ ]:
#week-3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
file_path=''
data=pd.read_csv("Advertising.csv")
print("Dataset Preview:")
print(data.head())
print("\nChecking for missing value:")
print(data.isnull().sum())
x=data[['TV','Radio','Newspaper']]
y=data['Sales']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)
print("\nModel Coefficients:")
print("Intercept: ",model.intercept_)
print("Coefficients:",model.coef_)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("\nModel Evaluation:")
print("Mean Squared Error:",mse)
print("R-squared:",r2)
plt.scatter(y_test, y_pred, color='blue', alpha=0.5)
plt.xlabel("Actual Sales")
plt.ylabel("Predicted Sales")
plt.title("Actual vs Predicted Sales")
plt.grid()
plt.show()

In [25]:

#week-4

import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(x, y)

print("Classes:", model.classes_)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

print("Predicted probabilities:\n", model.predict_proba(x))
print("Predictions:", model.predict(x))
print("Model score:", model.score(x, y))
print("Confusion matrix:\n", confusion_matrix(y, model.predict(x)))
print("Classification report:\n", classification_report(y, model.predict(x)))
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)
print("Classes:", model.classes_)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)
print("Predicted probabilities:\n", model.predict_proba(x))
print("Predictions:", model.predict(x))
print("Model score:", model.score(x, y))
print("Confusion matrix:\n", confusion_matrix(y, model.predict(x)))
print("Classification report:\n", classification_report(y, model.predict(x)))


Classes: [0 1]
Intercept: [-1.04608067]
Coefficients: [[0.51491375]]
Predicted probabilities:
 [[0.74002157 0.25997843]
 [0.62975524 0.37024476]
 [0.5040632  0.4959368 ]
 [0.37785549 0.62214451]
 [0.26628093 0.73371907]
 [0.17821501 0.82178499]
 [0.11472079 0.88527921]
 [0.07186982 0.92813018]
 [0.04422513 0.95577487]
 [0.02690569 0.97309431]]
Predictions: [0 0 0 1 1 1 1 1 1 1]
Model score: 0.9
Confusion matrix:
 [[3 1]
 [0 6]]
Classification report:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10

Classes: [0 1]
Intercept: [-3.51335372]
Coefficients: [[1.12066084]]
Predicted probabilities:
 [[0.97106534 0.02893466]
 [0.9162684  0.0837316 ]
 [0.7810904  0.2189096 ]
 [0.53777071 0.46222929]
 [0.27502212 0.7249778

In [ ]:
!pip install neattext


In [ ]:
import neattext.functions as nfx
print(nfx.remove_puncts("Hello, World!"))  # Test function


In [17]:
#week 5
import pandas as pd
import numpy as np
df = pd.read_csv("netflix_titles.csv")
print(df.head())
print(df['type'].value_counts())
print(df['rating'].value_counts())
import neattext.functions as nfx
import neattext.functions as nfx
df['title'] = df['title'].apply(lambda x: x.lower()) 
df['title'] = df['title'].apply(nfx.remove_stopwords) 
print(df.head())


  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1      s2  TV Show          Blood & Water              NaN   
2      s3  TV Show              Ganglands  Julien Leclercq   
3      s4  TV Show  Jailbirds New Orleans              NaN   
4      s5  TV Show           Kota Factory              NaN   

                                                cast        country  \
0                                                NaN  United States   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                NaN            NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min   
1  September 24, 2021          2021  TV-MA  2 Seasons   
2  September 24, 2021        

In [11]:
!pip install neattext

/Users/tejsai/.zshenv:export:1: not valid in this context: hello.java
