In [2]:
import numpy as np

In [4]:
h=[30,20,5,7,8,9]
h

[30, 20, 5, 7, 8, 9]

In [8]:
type(h)

list

In [45]:
#adding number 7 to the given  list
d=[]
for i in h:
    d.append(i+7)

In [47]:
d

[37, 27, 12, 14, 15, 16]

In [49]:
#squaring numbers in  a tuple
#trick:by converting tuple into a list
s=(1,3,4,5,6,9)
type(s)

tuple

In [53]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
    s=tuple(k)


In [55]:
s

(1, 9, 16, 25, 36, 81)

In [63]:
#appending numbers >50 to the list
g=[]
for i in s:
    if i>50:
        g.append(i)

In [65]:
g

[81]

In [67]:
#adding nums to  arrays
#no need of loops for perfo oper
arr=np.array([20,30,40,50,60,70,80,90])
arr+8

array([28, 38, 48, 58, 68, 78, 88, 98])

In [71]:
arr%8

array([4, 6, 0, 2, 4, 6, 0, 2])

In [73]:
arr<60

array([ True,  True,  True,  True, False, False, False, False])

In [77]:
k=[1,2,3,44,5,56,77]
index=[]
for i in range(len(k)):
    if k[i]>20:
        index.append(i)

In [79]:
index

[3, 5, 6]

In [81]:
i

6

In [83]:
k

[1, 2, 3, 44, 5, 56, 77]