In [4]:
import numpy as np
t=[10,20,30,40,50,60]
arr=np.array(t)
arr

array([10, 20, 30, 40, 50, 60])

In [10]:
np.mean(arr)

35.0

In [12]:
np.median(arr)

35.0

In [16]:
np.var(arr)

291.6666666666667

In [18]:
np.std(arr)

17.07825127659933

In [20]:
np.max(arr)

60

In [22]:
np.min(arr)

10

In [32]:
"""a=[1,2,3,4,5]
median(q1)=3
quartile(q2)=1+2/2
q3=4+5/2"""
np.quantile(arr,0.25)
#0.25,0.5,0.75

22.5

In [44]:
r=np.random.rand(2,3)
r

array([[0.60396898, 0.95406263, 0.95901837],
       [0.51342301, 0.15576971, 0.94604404]])

In [54]:
l=np.random.rand(5,2,3)
l
#2,3  are dimensions

array([4.51165327, 4.75317356, 4.16617148])

In [64]:
n=np.random.normal(10,2,(4,4))
n
#NORMAL DISB..

array([[10.56992749, 13.03031289, 14.8453569 , 10.7830442 ],
       [10.72056962, 10.05690571,  9.912201  ,  8.67251008],
       [11.4436714 , 12.89972374, 12.08063181,  5.70450807],
       [14.41031328,  9.7398328 , 10.74672935, 11.72845998]])